version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:9000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgresql-Cine-16.db.render.com
      DB_PORT: 5432
      DB_DATABASE: postgresql_cine_yvk9
      DB_USERNAME: postgresql_cine_yvk9_user
      DB_PASSWORD: IYlIbKyqbTXcQ1IreCVau9973WJq3iLm
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgresql_cine_yvk9_user
      POSTGRES_PASSWORD: IYlIbKyqbTXcQ1IreCVau9973WJq3iLm
      POSTGRES_DB: postgresql_cine_yvk9
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
