version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"  # Mapea el puerto 80 del contenedor al puerto 8080 de tu máquina
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgresql-Cine-16.db.render.com
      DB_PORT: 5432
      DB_DATABASE: postgresql_cine_yvk9
      DB_USERNAME: postgresql_cine_yvk9_user
      DB_PASSWORD: IYlIbKyqbTXcQ1IreCVau9973WJq3iLm
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge