version: '3.8'

services:
  # Servicio para PHP-FPM
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www  # Mapea el código de tu proyecto al contenedor
    expose:
      - "9000"  # Solo accesible entre contenedores

  # Servicio para Nginx
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Archivo principal de configuración
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Archivo específico del servidor
      - .:/var/www  # Código de tu aplicación
    ports:
      - "80:80"  # Expone el puerto 80
    depends_on:
      - php  # Espera a que el contenedor PHP esté listo
    networks:
      - app-network

  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgresql_cine_yvk9
      POSTGRES_USER: postgresql_cine_yvk9_user
      POSTGRES_PASSWORD: IYlIbKyqbTXcQ1IreCVau9973WJq3iLm
    ports:
      - "5432:5432"  # Expone el puerto 5432 para acceso público
    networks:
      - app-network

networks:
  app-network:
    driver: bridge