version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "8080:80"  # Expone el puerto 80 de Laravel al puerto 8080 de tu máquina
    volumes:
      - ./back/laravel:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgresql-Cine-16.db.render.com
      DB_PORT: 5432
      DB_DATABASE: postgresql_cine_yvk9
      DB_USERNAME: postgresql_cine_yvk9_user
      DB_PASSWORD: IYlIbKyqbTXcQ1IreCVau9973WJq3iLm
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgresql_cine_yvk9
      POSTGRES_USER: postgresql_cine_yvk9_user
      POSTGRES_PASSWORD: IYlIbKyqbTXcQ1IreCVau9973WJq3iLm
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge