services:
  db:
    image: mysql:8.2.0
    container_name: Mysql_DB
    volumes:
      - db-data2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    networks:
      - app-network

  laravel:
    build:
      context: .
      dockerfile: ./back/laravel/Dockerfile.dev
    container_name: Laravel
    working_dir: /var/www
    volumes:
      - ./back/laravel:/var/www
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network
    command: /bin/bash -c "sleep 20 && /wait-for-it.sh db:3306 --timeout=60 -- php artisan key:generate && composer install && cp /var/www/.env.example /var/www/.env && php artisan migrate:refresh --seed && php artisan serve --host=0.0.0.0 --port=8000"

  nuxt-app:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: Nuxt
    working_dir: /app
    volumes:
      - ./web/nuxt:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  node-sockets:
    build:
      context: ./back/node
      dockerfile: Dockerfile.dev
    container_name: NodeSockets
    working_dir: /app
    volumes:
      - ./back/node:/app
    ports:
      - "3102:3102"
    command: bash -c "npm install && node index.js"
    networks:
      - app-network

volumes:
  db-data2:

networks:
  app-network:
    driver: bridge