# Exported from Render on 2024-11-27T19:48:04Z
databases:
- name: postgresql-Cine
  databaseName: postgresql_cine_yvk9
  user: postgresql_cine_yvk9_user
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
