# Dockerfile para Nuxt.js
FROM node:18

# Establecer directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Compilar el proyecto
RUN npm run build

# Exponer el puerto 3000
EXPOSE 3000

# Comando para iniciar Nuxt
CMD ["npm", "run", "dev"]