# Dockerfile para producción de Nuxt
FROM node:18-bullseye

WORKDIR /app

# Copiar package.json y package-lock.json primero para aprovechar la caché
COPY ./web/nuxt/package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del proyecto
COPY ./web/nuxt ./

# Ejecutar la compilación de la aplicación Nuxt para producción
RUN npm run build

# Exponer el puerto 3000
EXPOSE 3000

# Comando para ejecutar la aplicación Nuxt
CMD ["npm", "run", "start"]